[serve]
address = "0.0.0.0"
port = 3001

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-i", "input.css", "-o", "app.css"]

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:3000/"
