FROM rust:latest AS build-env

WORKDIR /app

COPY . /app

RUN cargo test -p backend

RUN cargo build --release -p backend

FROM rust:slim AS final

COPY --from=build-env /app/target/release/backend /

EXPOSE 3000

CMD [ "./backend" ]
